config/routes.rb
Rails.application.routes.draw do
  resources :feeds
    root 'blogs#new'
  resources :contacts
  get 'sessions/new'

    resources :blogs do
        collection do
            post :confirm
        end
    end

      resources :users
      resources :sessions, only: [:new, :create, :destroy]
      resources :favorites, only: [:create, :destroy]

      if Rails.env.development?
          mount LetterOpenerWeb::Engine, at: "/letter_opener"
      end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    validates :title, :content, presence: true
    validates :content, length: { in: 1..140 }
    mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :session_login, only: [:new, :edit, :show]
  def index   #indexアクションの作成
    @blogs = Blog.all
    # binding.pry
    # render 'index'
  end
  
  def new
    if params[:back]
    @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id  #ここで、user_idに値を入れないといけない
    # puts "--------------debug"
    # puts @blog.user_id   
    render :new if @blog.invalid?
  end
  
  def create  #createアクションの作成
  @blog = Blog.new(blog_params)
   @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
   puts "--------------debug"
   puts @blog.user_id
   # @blog = current_user.blogs.build(blog_params)
  
   if @blog.save
     BlogMailer.blog_mail(@blog).deliver  ##追記
    redirect_to blogs_path, notice: "Blog was successfully"
   else
    render 'new'
   end
  end
  
  def show  #詳細ページ表示
    # params[:id]
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  
  def edit  #編集画面を表示
    @blog = Blog.find(params[:id])
  end
  
  def update  #更新
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice:"ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy  #削除
      @blog.destroy
      redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  private        #StrongParametersの意味
  
  def blog_params 
    params.require(:blog).permit(:title, :content, :image) #permitの中身だけを反映させる
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def session_login
    if session[:user_id] == nil
      redirect_to new_user_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :feed_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %> 
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる",name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<!--<header>-->
<!--    <ul>-->
<!--      <li><a href="#">Listing Blogs</a></li>-->
<!--      <li><a href="#">トップページ</a></li>-->
<!--    </ul>-->
<!--</header>-->
<div class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Boot</a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav>
    <h1>Listing Blogs</h1>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    
    <td class = "img-td">
      <strong>Image:</strong>
      <%= image_tag(blog.image) %>
    </td>
    
    <td class = "img-td">
      <strong>投稿者:</strong>
      <%= image_tag(blog.user.image) %>
    </td>
    
    <% if current_user.id == blog.user_id %>
    <td><%= link_to 'Show', blog, class: 'btn btn-default' %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    <% else %>
    <td><%= link_to 'Show', blog, class: 'btn btn-default' %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br>
<%= link_to '新しくブログを投稿する', new_blog_path %>

</div>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>投稿確認</h1>
    <p>
      <strong>Image:</strong>
      <%= image_tag(@blog.user.image) %>
    </p>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<%= link_to '新しくブログを投稿する', new_blog_path %>
<%= link_to '一覧に戻る', blogs_path %>


  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>